[package]
name = "chip8-emu"
version = "0.1.0"
authors = ["ischeinkman <scheinkman.ilan@gmail.com>"]

[dependencies]
rand = "0.5.*"
sdl2 = "0.31.0"

[features]
default = []
log_fps = []
log_frames = []
"log_level=error" = []
"log_level=debug" = ["log_level=error", "log_fps"]
